name: test, build and push the application to itch.io
run-name: testing, building and pushing for ${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  activate:
    name: Activate license
    runs-on: ubuntu-latest
    steps:
    - uses: game-ci/unity-test-runner@v3
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: ${{ env.PROJECT_PATH }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}

