name: test, build and push the application to itch.io
on:
  workflow_dispatch: {}
jobs:
  activate:
    name: Activate license
    runs-on: ubuntu-latest
    steps:              
    - name: List Files Action
      uses: mirko-felice/list-files-action@v3.0.5
    - uses: game-ci/unity-test-runner@v3
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: ${{ env.PROJECT_PATH }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}

